### ISSUE TITLE
Dashboard_Page

### ISSUE THREAD

**Issue by alejandrogznz** [SHPE-at-UCI/clubs.uci.edu.shpe#12]
Dashboard page, page redirected to after logging/registering

**Comment by guilleeh** [comment]
- [ ] Resume drop off and View 
- [ ] SHPE familia leaderboards
- [ ] SHPE Calendar of events
- [ ] Points System
<img width="1440" alt="Screen Shot 2020-02-18 at 5 51 01 PM" src="https://user-images.githubusercontent.com/37254908/74794157-52aee180-5277-11ea-9ebd-7e5d9327f39b.png">
<img width="498" alt="Screen Shot 2020-02-18 at 5 51 09 PM" src="https://user-images.githubusercontent.com/37254908/74794158-5478a500-5277-11ea-9092-713074ac8daf.png">
<img width="498" alt="Screen Shot 2020-02-18 at 5 51 22 PM" src="https://user-images.githubusercontent.com/37254908/74794159-55113b80-5277-11ea-969a-18e770c7817f.png">
