### ISSUE TITLE
Create Login Table

### ISSUE THREAD

**Issue by Ramon024** [SHPE-at-UCI/clubs.uci.edu.shpe#25]
User, time and from what type of system they've logged in. One to one relationship.

**Comment by guilleeh** [comment]
How is your progress on this Ramon?

**Comment by guilleeh** [comment]
Bump

**Comment by Ramon024** [comment]
I created a new python file and it looks correct to me but I'm not sure how
to integrate it or test it to see if it'll work. Also I won't be able to go
to the meeting tomorrow but I will be there on Thursday.
