### ISSUE TITLE
Make Login Page Mobile Friendly

### ISSUE THREAD

**Issue by guilleeh** [SHPE-at-UCI/clubs.uci.edu.shpe#52]
As a user on my phone, if I access the login page I should be able to easily login by fitting the center container correctly in mobile.

**To-Do**
- Make login page mobile friendly. 
- Change "SHPE | UCI Portal" to "SHPE at UCI Portal"
- Integrate error message to be above the login container. Refer to image below for where it should be.
<img width="1440" alt="Screen Shot 2020-04-06 at 7 32 34 PM" src="https://user-images.githubusercontent.com/37254908/78624085-a1bbd080-783d-11ea-832c-77ccf23a2355.png">

**Comment by josueal1** [comment]
Upon visiting the SHPE-UCI website, It was difficult to know the status of the login. Preferred, a centered-box right above "login" with **Red background** color would be best! :)
