### ISSUE TITLE
Report Invalid Credentials as Red Alert

### ISSUE THREAD

**Issue by josueal1** [SHPE-at-UCI/clubs.uci.edu.shpe#55]
<img width="1424" alt="Screen Shot 2020-04-15 at 2 22 50 PM" src="https://user-images.githubusercontent.com/30352270/79390593-d65a1700-7f24-11ea-9fc0-560e0e3d3919.png">

Upon visiting the SHPE-UCI website, It was difficult to know the status of the system until I saw the hidden banner at the top. A centered-red box right above "login" would be great messaging!

**Comment by guilleeh** [comment]
Brenda is working on this exact feature as we speak! :)
