### ISSUE TITLE
SHPE public events google calendar 

### ISSUE THREAD

**Issue by josueal1** [SHPE-at-UCI/clubs.uci.edu.shpe#56]
<img width="1430" alt="Screen Shot 2020-04-15 at 2 18 18 PM" src="https://user-images.githubusercontent.com/30352270/79518674-86ec1780-8006-11ea-8857-bf0e6964ca4c.png">

**Feature request Motivation**
---
to attract more members to SHPE-UCI wide events, and create more easy access, transparency for anyone, not just our members

**Solution**
---
Request SHPE-UCI exec board to make a public google calendar, ask leads to save events here, and embed the html <iframe/> into a page.  No API required, just that snippet of code from google calendar

**Alternatives**
---
Create a whole calendar from scratch which would be more time consuming. https://wics.ics.uci.edu/events/

**Comment by guilleeh** [comment]
Any progress on this @Johan-Cuevas?
