### ISSUE TITLE
Alumni Detail Page

### ISSUE THREAD

**Issue by guilleeh** [SHPE-at-UCI/clubs.uci.edu.shpe#65]
**Is your feature request related to a problem? Please describe.**
When I click on an alumni after I search for them, I should be redirected to a more details page to find more info about them.

**Describe the solution you'd like**
I would like a dynamic route that will change its content based on the username entered in the url.
For instance: localhost:5000/search/guilleeh --> should give me details about the alumni with that name. We still haven't decided how we want to have unique user id's, so for now maybe use their ucinetid

**Describe alternatives you've considered**
Instead of a whole new window, maybe you can do a little drop down window, with all their details.

**Additional context**
You have freedom to choose how to implement this.

**Comment by guilleeh** [comment]
Currently if you click on a user, it will take you to the profile page of that user. Perhaps we could have a toggle on the right side or somewhere on the search page, that will only search for alumni, since right now it is searching for all members.

New tasks:
- Toggle on right side of screen to enable alumni search
- Alumni page can be similar to  profile page, ping me if you want some ideas

**Comment by josueal1** [comment]
> Currently if you click on a user, it will take you to the profile page of that user. Perhaps we could have a toggle on the right side or somewhere on the search page, that will only search for alumni, since right now it is searching for all members.
> 
> New tasks:
> 
>     * Toggle on right side of screen to enable alumni search
> 
>     * Alumni page can be similar to  profile page, ping me if you want some ideas

Making a new separate task for this `Filter Task`, marking the original as done @guilleeh
